from CircularLinkedList import CircularLinkedList

cll = CircularLinkedList()
cll.insert_at_beginning(5)
cll.insert_at_beginning(4)
cll.insert_at_beginning(3)
cll.insert_at_beginning(2)
cll.insert_at_beginning(1)
cll.insert_at_end(6)
cll.insert_at_end(7)
print(cll.traverse())
cll.insert_after_position(100, 5)
print(cll.traverse())
cll.delete_at_beginning()
print(cll.traverse())
cll.delete_at_beginning()
print(cll.traverse())
cll.delete_at_end()
print(cll.traverse())
cll.delete_at_end()
print(cll.traverse())
cll.insert_at_end(101)
cll.insert_at_end(102)
cll.insert_at_end(103)
print(cll.traverse())
cll.delete_after_position(3)
print(cll.traverse())
